microsoft/kata-containers

src/agent/Cargo.lock, src/agent/Cargo.toml, src/tardev-snapshotter/Cargo.lock, src/tardev-snapshotter/Cargo.toml
Marked CVEs for kata-containers-cc RPM:
https://github.com/advisories/GHSA-x4qr-2fvf-3mr5
https://github.com/advisories/GHSA-w2w6-xp88-5cvw
https://github.com/advisories/GHSA-r7jw-wp68-3xch
https://github.com/advisories/GHSA-f8vr-r385-rh5r
https://github.com/advisories/GHSA-f8vr-r385-rh5r
https://github.com/advisories/GHSA-g4h2-4wvh-grc5
https://github.com/advisories/GHSA-96jv-r488-c2rj
https://github.com/advisories/GHSA-7rrj-xr53-82p7
CVE-2022-4304
CVE-2023-0215
CVE-2023-0286
CVE-2023-0464
Packages affected:
simple_asn1 (removed after updating sequoia-openpgp, which is a parent dependency of simple_asn1)
bzip2
tokio
hyper/h2
openssl-src
Validation:
`cargo deny check advisories`
=> Update cargo packages to fix CVEs

src/tools/genpolicy/src/main.rs, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/utils.rs
Discussed with Dan about adding these two options to have feature parity with the `az confcom acipolicygen` tooling. If it needs to be refactored into some other form, please let me know
Usage in printing base64 policy to stdout:
`genpolicy -y pod.yaml --base64-out`
Usage in printing decoded policy to stdout:
`genpolicy -y pod.yaml --raw-out`
thanks!
=> adding print-policy and outraw options to genpolicy tool

src/agent/rustjail/src/container.rs
This makes it so that any container has access to `/dev/sev-guest` out of the box with no privileges required.
Since `/dev/sev-guest` isn't available yet, I've validated this change using `/dev/cpu_dma_latency` (original chmod 600) by:
1. Verifying that the device is present in the container.
2. Verifying that reading from the device from a container yields the same result as from the VM context.
=> agent: Make /dev/sev-guest available to containers

tools/osbuilder/rootfs-builder/cbl-mariner/rootfs_lib.sh
Delete some of the mariner packages from the Guest image, for faster
TEE memory measurement.
Signed-off-by: Dan Mihai <dmihai@microsoft.com>
=> rootfs: delete some of the mariner packages

tools/osbuilder/rootfs-builder/cbl-mariner/rootfs_lib.sh
The shell is useful for debugging.
=> rootfs: add back bash to mariner's rootfs

tools/osbuilder/rootfs-builder/cbl-mariner/rootfs_lib.sh
=> rootfs: add back coreutils to mariner's image

tools/osbuilder/rootfs-builder/cbl-mariner/rootfs_lib.sh
=> rootfs: add back ps to mariner's rootfs

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/src/policy.rs, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/hypervisor.go, src/runtime/virtcontainers/sandbox.go
Make sure the hash of an incoming Policy matches the value of the SNP Host Data field. The value of Host Data will be validated through Remote Attestation, outside of this patch.
=> runtime: agent: validate policy contents

src/runtime/config/configuration-clh-snp.toml.in, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/hypervisor_config_linux.go, tools/osbuilder/image-builder/image_builder.sh
- Add image build macro to change partition format for kernel's "dm-mod.create" command
- Allow for igvm + image usecase in kata shim
=> Add support to build enable dm-verity protected images

src/runtime/virtcontainers/clh.go
There are 10 segments in the ACPI tables, and CLH works better when it uses all of them.
=> runtime: use 10 PCI segments for the Guest

src/agent/src/policy.rs
When a request cannot be evaluated to true, OPA can return an empty response. It doesn't respond with "response = false" unless a default value of false has been defined.
Handle empty responses the same way as "response = false", thus allowing users to bypass those responses by using
AllowRequestsFailingPolicy := true.
=> policy: bypass empty response from OPA

src/agent/src/rpc.rs, src/runtime/virtcontainers/fs_share_linux.go
The changes handle k8's secrets volume update in terms of:
- create new timestamped directory in guest
- update the '..data' symlink to point to the new timestamped directory
- create user visible symlinks to newly created secrets
Limitation: Since the agent does not have a delete Api, the older timestamped directory and stale user visible symlinks exist in guest.
=> runtime: Fix k8 configmap/secrets update propagation with limitations when filesystem sharing is disabled.

src/agent/src/signal.rs, src/libs/kata-types/src/annotations/mod.rs
- kata-types: drop mut for variables that are not mutated
- agent: drop mut from variable which is not mutated
=> drop mut for variables that are not mutated to enable build with rust 1.72.0

src/tools/genpolicy/rules.rego
Print an allow_storage_options condition check before checking the condition for debuggability
=> Print an allow_storage_options condition check value earlier

tools/osbuilder/rootfs-builder/cbl-mariner/rootfs_lib.sh
This library is now a requirement in the UVM due to recent CBL-Mariner systemd changes
=> Avoid removing zstd-libs from the UVM

src/runtime/config/configuration-clh.toml.in
**Overview**
This pull request addresses a specific scenario within the Kata-Containers configurations where the sev_snp_guest is NOT set. The proposed change focuses on updating the default value of the `confidential_guest` property to `true` in [configuration-clh.toml.in](https://github.com/microsoft/kata-containers/blob/328e44092ef6ac9df192c567bcd9f5421016603d/src/runtime/config/configuration-clh.toml.in#L43C9-L43C9) file. This adjustment aims to facilitate the use of kernel and Kata-CC initrd by default, allowing smoother execution of confidential_guest paths when sev_snp_guest is absent.
**Changes Made**
Modified the targeted [configuration file](https://github.com/microsoft/kata-containers/blob/328e44092ef6ac9df192c567bcd9f5421016603d/src/runtime/config/configuration-clh.toml.in#L43C …
=> Enable Confidential Guest by Default in Non-SEV-SNP CC Handler Configuration

src/agent/samples/policy/yaml/pod/pod-spark.yaml, src/tools/genpolicy/src/pod.rs
Allow genpolicy to process Pod YAML files including topologySpreadConstraints.
=> genpolicy: add topologySpreadConstraints support

src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml, src/tools/genpolicy/src/registry.rs
This is not a requirement of the tool itself but of the `katapolicygen` python wrapper used in [confcom](https://github.com/Azure/azure-cli-extensions/blob/main/src/confcom/azext_confcom/kata_proxy.py) for writing tests that run in parallel. Previously the `layers_cache` folder would be concurrently written to and deleted depending on the settings of the tests, resulting in errors.
This PR proposes using temp folders instead of `layers_cache` and keeping the layer hashes in a central `policy.json` file that doesn't get deleted after running the tool instead of the `.verity` files nested in `layers_cache`. Because of the use of temporary folders, the cleanup process is a little nicer too.
Let me know if anything should be changed, thanks!
=> Update caching mechanism to allow for concurrent genpolicy runs

src/runtime/virtcontainers/clh.go
https://github.com/microsoft/CBL-Mariner/pull/6942 introduces a debug config file with confidential_guest=true and sev_snp_guest=false. This PR enables that config file to be used. See commit message for more info.
Local testing
=> runtime: disable protection check

.github/pull_request_template.md
I've created 3 new PR labels our repo:
* `upstream-missing`: PRs that are yet to be upstreamed.
* `upstream-not-needed`: PRs that have been merged upstream.
* `upstream-merged`: PRs that have been merged upstream.
To facilitate tracking, from now on each PR should be initially tagged as `upstream-missing` or `upstream-not-needed`.
If a PR is created with `upstream-not-needed`, its description should explain why it won't be upstreamed unless it's directly obvious.
When a change is merged upstream, the PR label should be changed to `upstream-merged` and a comment should be added linking to the upstream PR.
=> github: add `upstream-missing` label to PR checklist

src/tools/genpolicy/src/registry.rs
Create the cache file if it's not present, instead of panicking.
=> genpolicy: don't panic without cache file

src/agent/samples/policy/yaml/pod/pod-ubuntu.yaml, src/tools/genpolicy/src/pod.rs
Adds priorityClassName as a field in PodSpec interface.
This change allows generation of policy for pods specifying priority classes, which currently fails.
Generated a policy for pod having priorityClassName and created the pod on K8s with kata-cc runtime.
=> genpolicy: add priorityClassName as a field in PodSpec interface

src/tools/genpolicy/src/yaml.rs
Modified yaml.rs to prevent panic when genpolicy is called for a PodDisruptionBudget spec.
https://microsoft.visualstudio.com/OS/_workitems/edit/48139280/
_**Pipeline e2e tests:**_ https://dev.azure.com/mariner-org/mariner/_build/results?buildId=493910&view=results
**_Local test:_**
Spec:
Before:
After:
=> genpolicy: add support for PodDisruptionBudget spec

.github/workflows/static-checks.yaml, src/agent/rustjail/src/container.rs, src/agent/src/device.rs, src/agent/src/mount.rs, src/agent/src/storage/mod.rs
This is to make the agent static checks pass so that we can use them as a PR gate - see https://github.com/microsoft/kata-containers/actions/runs/7730187184/job/21075045370?pr=154
Note that because of a GH limitation, this change won't be reflected in the checks of this PR (but I was able to validate the 2nd commit locally). We'll have to first merge this PR and then monitor any subsequent PRs to validate this change.
=> ci: Fix agent static checks

src/tarfs/tarfs.c
Fixes related to rarely exercised paths like failure or partial failure paths, tiny block devices (e.g., size of a single sector), corrupted images, etc.
Upstreaming to kata-containers is not necessary because we are hosting this in a different repo. 
Built the kernel module locally in 5.15 and 6.1 kernels, booted an image with busybox, loaded the module, mounted a tarfs file system and used it.
=> tarfs reliability fixes

src/runtime/Makefile, src/runtime/config/configuration-clh.toml.in, src/runtime/pkg/resourcecontrol/cgroups.go, tools/osbuilder/rootfs-builder/rootfs.sh
Turns out we can start vanilla Kata pods pretty much out of the box with msft-main. This PR just tweaks the vanilla config file and patches the runtime to unblock the debug console. I'm surprised we still need the runtime change, but I've verified the debug console doesn't work without that patch.
See microsoft/CBL-Mariner#6942 for specs changes.
* Local building and running incl. with new virtiofsd
* See microsoft/CBL-Mariner#6942 for conformance results
=> Adapt code for vanilla Kata

src/tardev-snapshotter/tarindex/src/lib.rs
Enable tarindex to handle symlink name with special characters or length longer than the 100 limit by duplicating it before the string table.
- Local testing with tarindex execuatable.
- Manual AKS cluster testing with "registry.k8s.io/e2e-test-images/agnhost:2.40" image. This update creates the previously skipped `/etc/ssl/certs/ca-cert-NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem symlink`.
- RPM build: [510540](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510540&view=results)
- Image build: [510563](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510563&view=results)
- Conformance test: [510729](https://dev.azure.com/mariner-org/mariner/_build/results?buildId=510729&view=results)
- Performance test: …
=> tarindex: Add special symlink name handling

src/tools/genpolicy/genpolicy-advanced-command-line-parameters.md, src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/src/config_map.rs, src/tools/genpolicy/src/daemon_set.rs, src/tools/genpolicy/src/deployment.rs, src/tools/genpolicy/src/job.rs, src/tools/genpolicy/src/list.rs, src/tools/genpolicy/src/no_policy.rs, src/tools/genpolicy/src/obj_meta.rs, src/tools/genpolicy/src/pod.rs, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/replica_set.rs, src/tools/genpolicy/src/replication_controller.rs, src/tools/genpolicy/src/secret.rs, src/tools/genpolicy/src/settings.rs, src/tools/genpolicy/src/stateful_set.rs, src/tools/genpolicy/src/utils.rs, src/tools/genpolicy/src/yaml.rs
genpolicy sync upstream [2/3]
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=547205&view=ms.vss-test-web.build-test-results-tab [pass]
=> genpolicy sync upstream [2/3]

src/agent/src/device.rs, src/agent/src/storage/fs_handler.rs, src/agent/src/storage/mod.rs, src/runtime/pkg/direct-volume/utils.go, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/kata_agent.go
This PR handles parsing of mount objects in pod OCI spec to filter out SMB/CIFS mounts and create appropriate volume object for the same, having _target path_ set to a path inside pod VM (i.e guest UVM). The changes, further modify the container mount objects to bind-mount to the _target path_.
=> Add support to handle SMB mounts

src/tools/genpolicy/.gitignore, src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml, src/tools/genpolicy/Makefile, src/tools/genpolicy/src/main.rs, src/tools/genpolicy/src/utils.rs, src/tools/genpolicy/src/version.rs.in
Add a --version flag to the genpolicy tool that prints the current version
Add --version flag
`
$ target/debug/genpolicy -v
Kata Containers policy tool (Rust): id: genpolicy, version: 3.2.0-azl0.genpolicy1, commit: ffc72e513cee8b5686df20c04abf5cec77de8236
`
dev: instead of `cargo build`, we'd use `LIBC=gnu BUILD_TYPE= make` (`cargo build` still works, but you'll need to use `LIBC=gnu BUILD_TYPE= make` the first time at least to generate version.rs and not get a compile error)
release: instead of `cargo build --release`, we'd use `LIBC=gnu make` (Here we'll want to stick to `LIBC=gnu make` as this will embed the correct commit information to release binary)
Make build method is incompatible on Windows. For Windows releases:
- set `src/version.rs` with correct commit info
- `cargo build …
=> genpolicy: add --version flag

src/agent/src/main.rs
Linux kernel generates a panic when the init process exits. The kernel is booted with panic=1, hence this leads to a vm reboot.
When used as a service the kata-agent service has an ExecStop option which does a full sync and shuts down the vm. This patch mimicks this behavior when kata-agent is used as the init process.
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=552636&view=ms.vss-test-web.build-test-results-tab
=> agent: shutdown vm on exit when agent is used as init process

src/tools/genpolicy/src/registry.rs, src/tools/genpolicy/src/registry_containerd.rs
Add missing cache improvements specifically missing in containerd pull. I'm not sure how I missed this: It was already using layers-cache.json and it produces the exact same cache after using these changes.
These improvements are already included in https://github.com/kata-containers/kata-containers/pull/9530 and based on https://github.com/microsoft/kata-containers/pull/113
https://dev.azure.com/mariner-org/mariner/_build/results?buildId=555763&view=results
=> genpolicy: add missing cache improvements

src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml
Bump release version to 3.2.0-azl1.genpolicy0
=> genpolicy: bump release version

.github/workflows/commit-message-check.yaml, .github/workflows/move-issues-to-in-progress.yaml
Upstream recently removed the requirement for commit messages to have the `Fixes: #XXX` line. Cherry-picking that change so that we can make the commit check required in our fork.
=> ci: cherry-pick relaxed commit check from upstream

.github/pull_request_template.md, .github/workflows/check-samples.yaml, src/tools/genpolicy/update_policy_samples.py
```
This adds a GitHub Action workflow to check that the policy samples have
been updated with each PR. We'll add it as a required check to catch
policy errors earlier in the dev process.
I also tweaked the update script to have better error handling, and I
simplified the PR template to make it more readable.
```
=> ci: add check for policy samples 

src/tools/genpolicy/update_policy_samples.py
Allow all users to pull images by using containerd instead of having to worry about this tool potentially creating files that the caller of update_policy_samples.py doesn't own.
Granting all users access to containerd is also consistent with the behavior of upstream Kata CI.
If any users really need to execute genpolicy as root, hopefully executing this entire script as root is good enough for them.
=> samples: don't execute genpolicy as root user

src/tools/genpolicy/.gitignore, src/tools/genpolicy/update_policy_samples.py
Enable genpolicy's dm-verity root hash cache when updating the sample files, to potentially achieve faster update policy script execution.
Also, this is an additional opportunity to test multiple instances of genpolicy synchronizing their access to the cache files.
=> samples: use the dm-verity root hash cache

src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PayloadConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_payload_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
Update sev_snp param serialization to make it
match against cloud-hypervisor v38.0.72.
See https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5628/file s#diff-c235a65d9dfdc1392f1c9546df912679bbdd74138316a04d9cfd53ef8fe1f907R 527
Update plataform config param from `sev` to `sev_snp`
This was done by updating cloud-hypervisor.yaml and running `make generate-client-code && make go-fmt`
=> virtcontainers: update sev_snp param serialization

src/agent/samples/policy/yaml/webhook3/dns-test.yaml, src/agent/samples/policy/yaml/webhook3/many-layers.yaml
The two samples define Pod overhead values. When testing these samples on clusters where different podOverhead values are defined by the respective runtime classes, the tests fail as the values need to match, see: /plugin/pkg/admission/runtimeclass/admission.go in the kubernetes GitHub repository. Hence, removing the overhead definitions.
Re-ran update_policy_samples.py. No change
As stated, testing failed when using a runtimeClass with different podOverhead value.
=> genpolicy: update policy samples

src/tools/genpolicy/policy_samples.json, src/tools/genpolicy/update_policy_samples.py
Add the new category for tests we want to run genpolicy against, but not run them in deployments (as the name suggests, we cannot run those).
Ran `update_policy_samples.py` and observed that the `incomplete_init` samples would still be processed
=> samples: introduce incomplete_init category

src/agent/Makefile, src/runtime-rs/Makefile, src/tools/kata-ctl/Makefile, src/tools/log-parser/Makefile, tools/osbuilder/Makefile, tools/osbuilder/rootfs-builder/rootfs.sh, tools/osbuilder/scripts/lib.sh
Cherry-picking changes made upstream. Will help make progress with: https://github.com/microsoft/kata-containers/pull/204
Upstream CI
=> Cherry-pick upstream PR #9825: osbuilder: allow rootfs builds w/o git or version file deps

src/tardev-snapshotter/tardev-snapshotter.service
At the moment, we have circular dependencies between tardev-snapshotter.service and containerd.service. Specifically, containerd.service needs tardev-snapshotter.service to run any CC pods, while tardev-snapshotter.service needs containerd.service to download image layers. This dependency will be eliminated once we switch to using remote-snapshotter. 
Currently, tardev-snapshotter.service's binding to containerd.service gets delayed, and we won't be able to run any CC pods until the boot process is completed. It doesn't matter which service starts first. 
Based on the current logic, it makes more sense to use WantedBy=kubelet.service in tardev-snapshotter.service, as we won't be able to start any CC pods without kubelet. This is also what we have been using by having `sed -i -e …
=> tardev: update tardev-snapshotter.service

src/agent/src/policy.rs, tests/integration/kubernetes/k8s-exec-rejected.bats
1. Use the new value of AllowRequestsFailingPolicy after setting up a new Policy. Before this change, the only way to enable AllowRequestsFailingPolicy was to change the default Policy file, built into the Guest rootfs image.
2. Ignore errors returned by regorus while evaluating Policy rules, if AllowRequestsFailingPolicy was enabled. For example, trying to evaluate the UpdateInterfaceRequest rules using a policy that didn't define any UpdateInterfaceRequest rules results in a "not found" error from regorus. Allow AllowRequestsFailingPolicy := true to bypass that error.
3. Add simple CI test for AllowRequestsFailingPolicy.
These changes are restoring functionality that was broken recently by commmit 11f78ae7010bd0b262b10939960b9fa6ea2b3b51.
=> agent: fix the AllowRequestsFailingPolicy functionality

src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml
Bump release version to 3.2.0-azl1.genpolicy1
=> chore: bump release version

tools/osbuilder/Makefile, tools/osbuilder/node-builder/azure-linux/README.md, tools/osbuilder/node-builder/azure-linux/uvm_build.sh
Allow setting SVN parameter for IGVM build scripting
Ran `IGVM_SVN=10 make all-confpods`. This yields the following:
```
...
/home/azureuser/kata-containers/tools/osbuilder/igvm-builder/igvm_builder.sh -o /home/azureuser/kata-containers/tools/osbuilder -s 10
IGVM builder script
-- OUT_DIR -> /home/azureuser/kata-containers/tools/osbuilder
-- SVN -> 10
-- DISTRO -> azure-linux
-- MODE -> build
igvm_lib.sh file found. Loading content
Reading Kata image dm_verity root hash information from root_hash file
igvm_lib.sh file found. Loading content
Building (debug) IGVM files and creating their reference measurement files
{'x-ms-sevsnpvm-guestsvn': '10', 'x-ms-sevsnpvm-launchmeasurement': '2785583f67d6a72a4e3f4ac3945ca6ee10bf59d2b12d865e5e16f1dc2b4e9db5a99e22eeb6f2fd8277fc6e4747369557'} …
```
=> tools: Enable setting IGVM SVN

.gitignore, tools/osbuilder/node-builder/azure-linux/Makefile, tools/osbuilder/node-builder/azure-linux/README.md, tools/osbuilder/node-builder/azure-linux/package_build.sh, tools/osbuilder/node-builder/azure-linux/package_install.sh, tools/osbuilder/node-builder/azure-linux/uvm_build.sh
See commit message.
Local build as described in commit message.
=> node-builder: introduce BUILD_TYPE variable

tools/osbuilder/node-builder/azure-linux/Makefile, tools/osbuilder/node-builder/azure-linux/README.md, tools/osbuilder/node-builder/azure-linux/package_install.sh
See commit.
NOT tested by me yet.
=> node-builder: introduce SHIM_REDEPLOY_CONFIG

src/tools/genpolicy/Dockerfile
Update Dockerfile for building genpolicy using an Azure Linux container. OpenSSL gets linked statically, thus allowing genpolicy to work on various other distros too.
=> genpolicy: update Dockerfile

docs/how-to/how-to-enable-storage-in-confidential-pods.md
Updates our docs to mention a limitation related to securityContext. I've reproed this locally for local storage, and Azure Disk is most likely affected too as the transport is the same.
See commit. Internal bug: https://microsoft.visualstudio.com/OS/_workitems/edit/53880968
=> docs: Add more limitations for AKS-CC storage

tools/osbuilder/node-builder/azure-linux/README.md
- Sanitize containerd config snippet
- Set podOverhead for Kata runtime class
- Manual deployments
=> node-builder: Adapt README instructions

.github/pull_request_template.md
pr_template: remove genpolicy windows support
check from PR template
We don't support genpolicy for windows as of 3.2.0.azl1.genpolicy1
n/a
=> pr_template: remove genpolicy windows support

tools/osbuilder/node-builder/azure-linux/uvm_build.sh, tools/osbuilder/rootfs-builder/rootfs.sh
- Revert the initial check PR introduced in fork: https://github.com/microsoft/kata-containers/commit/6f4a49c9b40c975654d7629986595b8cfc80b9a0
- Consume two upstream commits that achieve the same:
- https://github.com/kata-containers/kata-containers/commit/b7a184a0d8d6931ab0cfa76a97ed137500cb7e53
- https://github.com/kata-containers/kata-containers/pull/10389/files
Internal CI, package/image build and AKS image tests
=> tools: Align AGENT_POLICY_FILE check in rootfs-builder with upstream

tools/osbuilder/node-builder/azure-linux/README.md, tools/osbuilder/node-builder/azure-linux/common.sh, tools/osbuilder/node-builder/azure-linux/uvm_build.sh, tools/osbuilder/rootfs-builder/cbl-mariner/config.sh
Change recipe to assume Azure Linux 3 as the build path.
Sustain instructions to be able to build on Azure Linux 2 as production AKS nodes are on Azure Linux 2.
- Manual: Following the recipe on AzL2, deploying pods.
=> node-builder: Use Azure Linux 3 as default path

src/runtime/virtcontainers/clh.go
The cloud-hypervisor's logging behavior is different than described in the CLH log levels comment in clh.go. This PR updates the comment to accurately reflect the behavior as implemented in cloud-hypervisor: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/src/main.rs#L555 
A single -v filters at the 'Info' level, not 'Warn'. Info is the desired level of verbosity to not add too much noise to the output. 
No functional change.
=> Fix logging verbosity comment to accurately reflect clh behavior

src/runtime/virtcontainers/clh_test.go, src/runtime/virtcontainers/hypervisor_test.go
This commit fixes make test for virtcontainers. It fixes:
a. hypervisor_test::TestAssetPath by adding igvm asset path.
b. clh_test::TestCreateVM by setting testData expectError to false for ConfidentialGuest test config.
This is needed because we have allowed noneProtection for test purposes for Confidential configuration.
Fix `make test` for src/runtime/virtcontainers.
Local run tests:
go test --run TestAssetPath
go test --run TestClhCreateVm
=> runtime: Fix make test for virtcontainers.

.github/workflows/static-checks.yaml
Install libdevmapper for agent make test check.
Install device mapper for agent static build checks for both make check & make test.
This fixes the `libdevicemapper.h` not found when compiling devicemapper-sys crate.
=> ci: install libdevmapper for agent static checks

src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
With full debug logging enabled there might be around 1,500 redials so skip logging some of these failures to avoid flooding the log.
=> runtime: skip logging some of the dial errors

src/agent/samples/policy/yaml/pod/pod-one-container.yaml, src/tools/genpolicy/src/obj_meta.rs
This prevents a deserialization error when uid is specified.
Cherry pick from https://github.com/kata-containers/kata-containers/commit/711d12e5db8caa757fafc587f809b4e901cb91a5
test run: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=688524&view=results
=> policy: ignore optional metadata uid field

src/overlay/Makefile, src/tardev-snapshotter/Makefile, src/tarfs/Makefile, src/utarfs/Makefile
This commit fixes make static-checks.
=> ci: Fix make static-checks

src/runtime/virtcontainers/clh.go
The commit cherry picks upstream changes merged in PR 10548.
=> runtime: Set memory config shared=false when shared_fs=None in CLH

src/runtime/virtcontainers/clh.go
This commit introduces changes merged in upstream PR 9153 of relaxing the timeout for calling CLH's CreateVM+BootVM APIs. Further, the commit increases the timeout to 100s to handle guest boot with large memory requests.
=> runtime: relax timeout for CreateVM + BootVM in CLH

src/agent/src/device.rs
This commit fixes failing tests
- test_get_device_name()
- test_virtio_blk_matcher()
The changes correctly constructs VirtioBlkPciMatcher.
Commit https://github.com/microsoft/kata-containers/commit/c905577ecadc7baf60b3c5a57f83d96c58ac2969 for hotplugging block devices on PCI segments >= 1 modified VirtioBlkPciMatcher::new() to take the complete pci sysfs
path instead of only the relative path.
=> agent: fix make test

src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml
Bump genpolicy version to 3.2.0-azl3.genpolicy2
=> chore: bump genpolicy bump genpolicy version

src/runtime/config/configuration-clh.toml.in, src/runtime/pkg/katautils/config.go, src/runtime/virtcontainers/clh.go, tools/osbuilder/image-builder/image_builder.sh
Reduce the memory usage for the guest image by:
1. Using a smaller guest image size.
2. Using virtio-blk instead of pmem for the guest image.
=> reduce the memory usage for the guest image

src/runtime/pkg/katautils/config.go, src/runtime/virtcontainers/hypervisor.go, tools/osbuilder/node-builder/azure-linux/package_build.sh
After these changes:
1. The value of the K8s runtime class memory overhead:
- Covers the memory usage from all the Host-side components (mainly the Kata Shim and the VMM).
- Doesn't include the memory usage from any Guest-side components.
2. The value of a pod memory limit specified by the user:
- Is equal to the memory size of the Pod VM.
- Includes the memory usage from all the Guest-side components (mainly user's workload, the Guest kernel, and the Kata Agent)
- Doesn't include the memory usage from any Host-side components.
=> runtime: improved memory overhead management

src/runtime/config/configuration-fc.toml.in, src/runtime/config/configuration-qemu.toml.in
- We only ever tested the fork changes for changed memory allocation behavior with CLH+MSHV
- Remove these options as we don't use QEMU/FC
N/A
=> runtime: Remove unused VMM options for mem alloc

src/tardev-snapshotter/src/snapshotter.rs
=> Extend layer decompression based on mediatype label from containerd

src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml
Bump genpolicy version to 3.2.0-azl3.genpolicy3
=> chore: bump genpolicy version

src/agent/samples/policy/yaml/webhook/webhook-pod4.yaml, src/agent/samples/policy/yaml/webhook2/webhook-pod10.yaml
64Mi limit is insufficient after the changes from c7b8ee92025ee6c468a94c233994d6f9b6a00cf5. The lowest supported memory limit is 192Mi.
=> samples: use 256Mi pod memory limit

src/agent/src/policy.rs
The aim of this PR is to fix a regression introduced in https://github.com/microsoft/kata-containers/pull/273/files#diff-84f120758564e7adf93c69772f22eb04eaefcde3d30c01ddbe5a906f1611233d where rego error logs were no longer available after that change.
take_prints takes and clear prints per https://github.com/microsoft/regorus/blob/748c11cfa1319c808977194c1657e0fd866269be/src/engine.rs#L848 
Add back error logs by not calling take_prints twice.
tested locally: rego error logs are again printed as expected
=> agent: add back rego error logs

src/libs/kata-sys-util/src/mount.rs
Avoid repeated "unknown mount flag" log messages for tardev image layers mount options.
=> agent: avoid "unknown mount flag" for tardev

src/runtime/virtcontainers/sandbox.go
Skip logging empty lines of text from the Guest console output, if there are any such lines.
Without this change, the Guest console log from CLH + /dev/pts/0 has twice as many lines of text. Half of these lines are empty.
Fixes: #10737
Cherry-pick upstream commit 2e21f513756b4950ac203a0612b1d4c4071ea8a3
=> runtime: skip empty Guest console output lines

src/overlay/Cargo.lock, src/overlay/Cargo.toml, src/overlay/src/main.rs
In overlay, Replaces mount(8) with nix::mount to address limitations in handling multiple lowerdir entries for OverlayFS, ensuring compatibility with updated mount API behaviors.
- Manual validation using AKS cluster
- conformance test: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=712133&view=results
- performance test: https://dev.azure.com/mariner-org/mariner/_build/results?buildId=711484&view=results
=> overlay: use nix::mount for OverlayFS to overcome mounting limitations

src/tardev-snapshotter/src/snapshotter.rs
=> Add retry logic to image layer fetching and decompression

tools/osbuilder/image-builder/image_builder.sh, tools/osbuilder/rootfs-builder/rootfs.sh
1. Move the deletion of systemd units and files from image_builder.sh into rootfs.sh. 
- This allows other image file formats to benefit from the deletion of unnecessary systemd units and files, not just the rootfs-image format created by image_builder.sh.
- Also, image_builder.sh was deleting these files *after* it calculated the size of the rootfs files, thus missing out on the opportunity to possibly create a smaller image file.
2. Delete symbolic links to files being deleted.
=> rootfs: minor systemd file deletion cleanup

src/agent/src/config.rs, src/libs/kata-sys-util/src/protection.rs, src/libs/protocols/build.rs, src/tools/genpolicy/src/registry.rs
- unbreak build with rust v1.84
- some of the changes can be found in upstream PRs
- we should revisit the changes made by this PR once fork sources are more up to date with upstream sources
- changes are small and should be easy to detangle or reproduce
- manual build
- internal CI
=> Prepare for build with rust v1.84

.github/workflows/static-checks.yaml, src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml, src/tools/genpolicy/Makefile, src/tools/genpolicy/tests/main.rs, src/tools/genpolicy/tests/testdata/copyfile/pod.yaml, src/tools/genpolicy/tests/testdata/copyfile/testcases.json, src/tools/genpolicy/tests/testdata/createsandbox/pod.yaml, src/tools/genpolicy/tests/testdata/createsandbox/testcases.json, tools/packaging/static-build/tools/Dockerfile
The goal of this PR is to add a testing framework for policy. Compared with current ways of testing policy changes, these tests run fast and are self-contained, so no cluster is needed to run the tests. We also expect to improve test coverage by being able to test very specific request inputs that should be allowed or denied by the policy.
Cherry pick from https://github.com/kata-containers/kata-containers/pull/10068
These tests will:
- Take a pod yaml, generate it's policy, and set it in the regorus engine for testing
- Go through a list of requests and test if it's allowed or not against that policy
Same as upstream PR, the initial set of test cases is mostly for illustration and will be expanded incrementally.
We are also modifying the genpolicy makefile such that `make test` runs …
=> genpolicy: add crate-scoped integration test

.github/workflows/basic-ci-amd64.yaml, src/agent/rustjail/src/cgroups/notifier.rs, src/agent/src/rpc.rs, src/runtime/virtcontainers/kata_agent.go
Backporting kata-containers/kata-containers#10911
* Upstream tests
* https://dev.azure.com/mariner-org/mariner/_build/results?buildId=744537&view=results
* Reran flaky test https://dev.azure.com/mariner-org/mariner/_build/results?buildId=745515&view=results
=> agent: Fix race condition with cgroup watchers

tools/osbuilder/node-builder/azure-linux/README.md, tools/osbuilder/node-builder/azure-linux/package_install.sh
Using a symlink would create a cycle after calling this script again when copying the final configuration at line 74 so we just use cp instead.
Also, I moved this block to the end of the file to properly override the final config file.
Local build
=> node-builder: Fix SHIM_USE_DEBUG_CONFIG behavior

src/runtime/pkg/katautils/config.go, src/runtime/pkg/katautils/config_test.go
The documented behavior was that the clh loglevel was set to 1 if unspecified. This was in actuality 0; properly fix the default logic to reflect the documented/expected result.
Edit the config to enable_debug but don't specify a hypervisor loglevel. Observe with a deployed pod that its sandbox is running with -v (default 1 verbosity level)
=> config: Properly set default clh loglevel to 1

src/agent/Cargo.lock, src/agent/policy/Cargo.toml, src/agent/policy/src/policy.rs, src/agent/src/policy.rs, src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/tests/main.rs, src/tools/genpolicy/tests/testdata/createContainer/basic/pod.yaml, src/tools/genpolicy/tests/testdata/createContainer/basic/testcases.json, src/tools/genpolicy/tests/testdata/createContainer/legacy/pod.yaml, src/tools/genpolicy/tests/testdata/createContainer/legacy/testcases.json
Add test cases for basic and legacy requests to create pause container. These 2 tests provide a reasonable amount of coverage for CreateContainerRequest validation
=> policy: add tests for createContainerRequest

src/tools/genpolicy/Makefile
Use "cargo build --release" when BUILD_TYPE was not specified, or when BUILD_TYPE=release. The default "cargo build" behavior is to build in debug mode.
=> genpolicy: add support for BUILD_TYPE=debug

src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml
Bump genpolicy version to 3.2.0-azl5.genpolicy0
Genpolicy version bump for upcoming `3.2.0-azl5.genpolicy0` which corresponds to related https://github.com/microsoft/kata-containers/releases/tag/3.2.0.azl5
=> genpolicy: bump genpolicy version to 3.2.0-azl5.genpolicy0

src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml
bump genpolicy version to 3.15.0-aks0.genpolicy0
=> genpolicy: bump genpolicy version to 3.15.0-aks0.genpolicy0

src/tardev-snapshotter/Cargo.lock, src/tardev-snapshotter/Cargo.toml, src/tools/sign-oci-layer-root-hashes/Cargo.lock, src/tools/sign-oci-layer-root-hashes/Cargo.toml, src/tools/sign-oci-layer-root-hashes/src/registry_containerd.rs
- Remove tarindex dependencies from snapshotter and solar cargo.toml files
- Update `registry_containerd.rs` to use erofs instead of tarindex
- Tested locally by creating and starting a container using the tardev-snapshotter
=> Remove tarindex from snapshotter and solar dependencies

tools/osbuilder/node-builder/azure-linux/clean.sh, tools/osbuilder/node-builder/azure-linux/common.sh, tools/osbuilder/node-builder/azure-linux/package_build.sh, tools/osbuilder/node-builder/azure-linux/package_install.sh
For ease of debugging, install a configuration-clh-debug.toml for pod sandboxing as we do in Conf pods.
Introduce debug config for pod sandboxing to aid users in turning on debug logs, console. 
This is a portion of the original effort to produce full-fledged debug images. This was not consumed in our product for upstream ability concerns, so we've decided to go ahead with a smaller-scope change to add a debug config instead.
https://github.com/microsoft/kata-containers/pull/310/files#diff-45d6661afd5c14c07ae7a0a491df2e51cb0ad86c82b44be444250fe1373d99cfR81 
Ran make package and saw the new debug configuration produced under src/runtime/config
=> node-builder: Build and install debug configuration for pod sandboxing

src/common/Cargo.toml, src/common/src/constants.rs, src/common/src/lib.rs, src/tools/sign-oci-layer-root-hashes/Cargo.lock, src/tools/sign-oci-layer-root-hashes/Cargo.toml, src/tools/sign-oci-layer-root-hashes/src/main.rs, src/tools/sign-oci-layer-root-hashes/src/registry.rs, src/tools/sign-oci-layer-root-hashes/src/registry_containerd.rs, src/tools/sign-oci-layer-root-hashes/src/sign.rs, src/tools/sign-oci-layer-root-hashes/src/utils.rs
This PR updates oci-distribution (renamed to oci-client, ref: https://crates.io/crates/oci-client) to the latest version, and extends Solar to attach signatures to image manifest with a new command. 
The usage of the attach command:
```
solar \
--image $TEST_IMAGE \  OR --images <approved-container-images>
--use-cached-files \
--signer $CERT \
--key $KEY \
--passphrase pass: \
attach-signatures-to-image-manifest
```
=> Extend solar to attach signatures to image manifest

tools/osbuilder/image-builder/image_builder.sh
This reverts commit a1025659577e9d0e1259032f06bc4eae4afe672b.
That was a workaround for https://github.com/kata-containers/kata-containers/issues/7993, that has been fixed upstream.
=> image: revert don't insert the DAX header (#56)"

src/runtime/pkg/resourcecontrol/cgroups.go
This reverts commit 3cfdd53a88ee4f9704c957895b633601c4ac4475. Based on automated and manual testing, this commit is no longer required.
N/A
N/A
- manual testing
- internal automation (880636, 880974)
=> Revert "runtime: fix error when using the debug console"

tools/osbuilder/node-builder/azure-linux/README.md
As we adopted containerd2, we remove references to our prior forked containerd version.
N/A
N/A
N/A
=> docs: node-builder: Remove references to moby-containerd-cc

tests/common.bash
This makes the following check green:
```
[Static checks / static-checks (make static-checks)
```
=> cherry-pick: ci: static-checks: Don't hardcode default repo branch
