tools/osbuilder/README.md, tools/osbuilder/rootfs-builder/mariner/Dockerfile.in, tools/osbuilder/rootfs-builder/mariner/config.sh, tools/osbuilder/rootfs-builder/mariner/rootfs_lib.sh
Add mariner rootfs and image entry
=> Add mariner rootfs and image entry

.github/CODEOWNERS
Signed-off-by: Chris Co <chrco@microsoft.com>
=> CODEOWNERS: Add initial codeowners file

src/runtime/pkg/resourcecontrol/cgroups.go
Add support for the Microsoft Hypervisor, in addition to KVM.
=> Add support for MSHV

src/runtime/pkg/resourcecontrol/cgroups.go, tools/osbuilder/README.md, tools/osbuilder/rootfs-builder/mariner/Dockerfile.in, tools/osbuilder/rootfs-builder/mariner/config.sh, tools/osbuilder/rootfs-builder/mariner/rootfs_lib.sh
Add rootfs and image entry for Mariner
=> Add rootfs and image entry for Mariner

src/agent/src/mount.rs, src/tardev-snapshotter/Cargo.lock, src/tardev-snapshotter/tarfs-defs/Cargo.toml, src/tardev-snapshotter/tarfs-defs/src/lib.rs, src/tardev-snapshotter/tarindex/Cargo.toml, src/tardev-snapshotter/tarindex/src/lib.rs, src/tarfs/tarfs.c, src/tools/genpolicy/Cargo.lock
There are two fixes here:
1. Support for whiteouts
2. Fix the order of the layers
=> Fixes that allow nginx to run

src/runtime/config/configuration-clh-snp.toml.in, tools/osbuilder/rootfs-builder/cbl-mariner/config.sh, tools/osbuilder/rootfs-builder/rootfs.sh
- Remove unsuded disable_nesting_checks and add comments for unused SNP configs by CLH
- Remove extra rootfs package definition
=> Update clh-snp config and remove extra rootfs package definition

src/runtime/pkg/katautils/create.go
- Add missing systemd command line parameters for initrd images
=> Append systemd kernel command line parameters for initrd

tools/osbuilder/image-builder/image_builder.sh
This is a workaround for
https://github.com/kata-containers/kata-containers/issues/7993.
=> image: don't insert the DAX header

src/agent/samples/policy/yaml/webhook3/dns-test.yaml, src/agent/samples/policy/yaml/webhook3/many-layers.yaml
Don't try to use someone else's cluster nodes!
=> policy: get sample pods to running state

src/tardev-snapshotter/src/snapshotter.rs
This is a workaround to snapshot names being different than what genpolicy expects.
Built and tested locally
https://microsoft.visualstudio.com/OS/_workitems/edit/47251546
=> tardev: only use the suffix of a pathname as the name

docs/how-to/README.md, docs/how-to/how-to-use-the-kata-agent-policy.md
=> docs: add agent policy how-to doc

tools/osbuilder/rootfs-builder/cbl-mariner/config.sh, tools/osbuilder/rootfs-builder/cbl-mariner/rootfs_lib.sh
Need to wait for kata meta-packages to show up on PMC
=> Revert "Add kata metapackage change"

.github/CODEOWNERS
This adds our team as reviewers for PRs automatically again.
=> github: copy CODEOWNERS from cc-msft-prototypes

src/libs/logging/src/lib.rs
Pick up commit f9f1d3a07197d26daeb51e3cc6883a2ef039a0bc from upstream, to avoid discarding debug!() log messages in kata-agent.
=> libs:logging: Fix logger

tools/osbuilder/node-builder/azure-linux/README.md
Updates to node-builder README:
- no longer install make package, is part of meta package
- remove superfluous popd
- add note on permissive policy for ConfPods UVM builds
Follow steps by hand
=> node-builder: Minor updates to README.md

src/tardev-snapshotter/src/snapshotter.rs, src/tardev-snapshotter/tardev-snapshotter.service
=> Improve tardev-snapshotter log levels

tools/osbuilder/node-builder/azure-linux/README.md
- with the latest 3.2.0.azl4 package on PMC, can remove OS_VERSION parameter and use the make deploy calls instead of copying files by hand for variant I (now aligned with Variant II)
- with the latest changes on msft-main, set the podOverhead to 600Mi
- manual deployment
=> node-builder: Updates to README.md

src/tools/genpolicy/tests/adapt_settings_for_tests.sh, src/tools/genpolicy/update_policy_samples.py
This keeps the repo changes clean while running update script and removes the need to remove the test settings at the end of the script
Ran update script and verify the samples remain the same as expected
=> samples: write test settings to /tmp

src/tools/sign-oci-layer-root-hashes/src/registry.rs
Adds more context to error messages for easier debugging. Adds missing `format!()` to the `Failed to create verity hash` error message.
=> Improve solar logging for error cases

tools/osbuilder/node-builder/azure-linux/package_install.sh
=> node-builder: fix package install main

tools/osbuilder/node-builder/azure-linux/package_install.sh
=> node-builder: fix package install syntax

.github/CODEOWNERS
Update CODEOWNERS for erofs-main
=> Update CODEOWNERS for erofs-main

src/runtime/virtcontainers/pkg/cloud-hypervisor/Makefile, versions.yaml
- Change Makefile to point to fork
- Change versions.yaml to point to proper version on fork
- Do not regenerate the binding - the current definitions are invalid
- Definitions will be fixed with upcoming versions such as v41.0.120
- N/A
- N/A
- manual execution of `make all`, `make clean-generated-code`
=> Update cloud-hypervisor API reference

.github/workflows/codeql.yml
Enabling advanced CodeQL logic, re-adding upstream's codeql.yml with the only modifications being branch specifications. This should align fork and upstream CodeQL task logic.
N/A
N/A
Check: git diff origin/release/3.19.1..origin/ms-mahuber-patch-1 -- .github/workflows/codeql.yml
=> Re-add codeql.yml with proper branches

tools/osbuilder/node-builder/azure-linux/README.md
=> docs: node-builder: fix static check error

.github/workflows/zizmor.yaml
Cherry-picked from https://github.com/kata-containers/kata-containers/pull/11788
=> cherry-pick: ci: Run Zizmor on pushes to any branch
